# Generated by Django 6.0.6 on 2026-06-09 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur_1', models.ForeignKey(db_column='id_utilisateur_1', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_1', to=settings.AUTH_USER_MODEL)),
                ('id_utilisateur_2', models.ForeignKey(db_column='id_utilisateur_2', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_conversation', models.ForeignKey(db_column='id_conversation', on_delete=django.db.models.deletion.CASCADE, to='messagerie.conversation')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
