# Generated by Django 6.0.6 on 2026-06-09 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('plage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Disponibilite',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Format',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Matiere',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mentor', 'Mentor'), ('mentore', 'Mentoré')], max_length=10)),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Offre',
            },
        ),
        migrations.CreateModel(
            name='Offre_Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disponibilite', models.ForeignKey(db_column='id_disponibilite', on_delete=django.db.models.deletion.CASCADE, to='offres.disponibilite')),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.CASCADE, to='offres.offre')),
            ],
            options={
                'db_table': 'Offre_Disponibilite',
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='disponibilites',
            field=models.ManyToManyField(through='offres.Offre_Disponibilite', to='offres.disponibilite'),
        ),
        migrations.CreateModel(
            name='Offre_Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_format', models.ForeignKey(db_column='id_format', on_delete=django.db.models.deletion.CASCADE, to='offres.format')),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.CASCADE, to='offres.offre')),
            ],
            options={
                'db_table': 'Offre_Format',
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='formats',
            field=models.ManyToManyField(through='offres.Offre_Format', to='offres.format'),
        ),
        migrations.CreateModel(
            name='Offre_Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='offres.matiere')),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.CASCADE, to='offres.offre')),
            ],
            options={
                'db_table': 'Offre_Matiere',
            },
        ),
        migrations.AddField(
            model_name='offre',
            name='matieres',
            field=models.ManyToManyField(through='offres.Offre_Matiere', to='offres.matiere'),
        ),
    ]
